[package]
name = "renewables"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
redis = { version = "0.23", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
chrono = "0.4.41"